### ISSUE TITLE
No IDF Syntax Highlighting

### ISSUE THREAD

**Issue by JustinShultz** [bigladder/atom-language-energyplus#1]
I am unable to get the syntax Text Color and Highlighting feature to work for files with the extension .idf. I installing the language-energyplus package through the Atom Package Manager. The highlighting appears to be correct for .err, .idd, and ModelKit but the highlighting is missing for .idf. 

I also tried uninstalling and reinstalling. Is this a know issue? Is there a simple fix?

Below are the language options I see when I try to change the language. 

![image](https://user-images.githubusercontent.com/3712065/50165641-4e71e780-02b3-11e9-8564-5f5134c921c7.png)

**Comment by aaron-boranian** [comment]
Hi @JShultz89, thanks for posting this issue. To apply syntax highlighting to IDF files, you should use the "Modelkit - EnergyPlus v9.0" language at the bottom of your screen shot. If that doesn't help, then we can set up a webinar so that you can share your screen and I can help you troubleshoot.

**Comment by JustinShultz** [comment]
Hi @aaron-boranian even with the ModelKit-EnergyPlus v9.0 selected I do not see syntax highlighting. I am trying to load an EnergyPlus 8.9.0 file, could that be causing a problem?

**Comment by aaron-boranian** [comment]
No, loading a v8.9 IDF shouldn't impact the color highlighting (see screen shot below of a v8.9 IDF that I opened in Atom).

![image](https://user-images.githubusercontent.com/15160917/50171043-8c204180-02ae-11e9-82d3-d823f334ebb3.png)

However, I will note that all of the auto-completed objects that are inserted by the package are for v9.0, which could have made changes to input fields (removing some, shifting them to different order, etc.) of objects you are using and cause your simulation to fail.

One other possibility is that your IDF is very large, and it's just taking Atom a while to load the file and apply the highlighting. However, you mentioned that you saw syntax highlighting in the IDD file, which is massive, so that may not be the culprit.

If you want to set up a webinar, my email address is aaron.boranian@bigladdersoftware.com.

**Comment by JustinShultz** [comment]
You might be onto something with the size of the file. I just checked the IDD file and realized that it is not loading either. I assumed it was because I saw the syntax highlighting option in the menu of my first message. I would love to setup a webinar to discuss more.

**Comment by JustinShultz** [comment]
As pointed out by @aaron-boranian, the issue is related to an Atom performance setting, as seen in the link below. 

https://github.com/atom/atom/pull/7130

This is not an issue specific to the atom-language-energyplus package. This issue can be closed.

**Comment by FueTsui** [comment]
Excuse me,I'm the same question. What's the solution to this problem?

**Comment by aaron-boranian** [comment]
@FueTsui if the size of your IDF is larger than 2MB, then Atom will not apply syntax highlighting and other features of the EnergyPlus Language Package. One possible solution for IDFs larger than 2MB is to "dissect" your IDF into multiple "sub-IDFs", then view and modify these "sub-IDFs" in the EnergyPlus Language Package.

If your IDF is smaller than 2MB, and the EnergyPlus Language Package is not applying syntax highlighting and other features correctly, then please open a new issue and attach your IDF.
